### ISSUE TITLE
Laser de Maderas

### ISSUE THREAD

**Issue by Agustoledo10** [pdepjm/2023-tp0-presentacion-tomasfiestas#1]
Buenas, como es el emprendimiento de laser de maderas, tenes alguna foto? Suena re interesante :0

**Comment by BorquezBelli** [comment]
Vengo por lo mismo, me interesa el emprendimiento

**Comment by tomasfiestas** [comment]
Buenas, por ahora esta muy verde pero porque sigo aprendiendo, se basa en agarrar imágenes y vectorizarlas para después poder pasarlas a una maquina laser y conseguir eso en mdf, mis ultimas "pruebas" fueron este cuadro de los merodeadores y unas cartas de Pokémon, se las dejo!!

![merodeadores](https://user-images.githubusercontent.com/129446256/229250482-8104aa30-4c0a-4e4f-ad54-cfdf1814fa74.jpg)
![pokemon](https://user-images.githubusercontent.com/129446256/229250496-b2e196d0-5138-4013-932c-a8142516fc15.jpg)
