### ISSUE TITLE
Recomendación 

### ISSUE THREAD

**Issue by NahuelLazarte** [pdepjm/2023-tp0-presentacion-tomasfiestas#5]
Si te interesan los libros, te recomiendo una página donde vas a encontrar online un monton de libros clásicos: https://www.ellibrototal.com/ltotal/ es como una especie de netflix de libros.

**Comment by tomasfiestas** [comment]
noooo es un golazo, no tenia ni idea de la existencia de esa pagina, me la guardo, gracias!!!
